dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: HXOlM52iRDi8oxMaKuJmps5kg8QLeuixkBcfBD6kdQV9UdG55OqdkkNQfnWL855WDzPeAkq4i9kB64QKLnXhtguwcdCnhYjyFxql3Jgdq6oGBVegm57So8oCkQqVOvzcVbbfxhxqxM58D9gxbLWDXbMbA3KY/puMY7dOC/25OWXpEDDKeSfgFDLRUqc9TM2YEnpGvrQrAKHUAuvYfRgNpfqlrtXs6sOWVvjdJmba45LND3HrW3ceLs9PeMafi/67+Qn1MoGUlnHN9HIkTYaYt9/XL3Ooyccf+Zy4qt6GW1g7mN6AArioTf+zDLuxg758t1Y1iwva/cFS1Ebp6X2aQZxIFIQ72RDiDusOPgteqfpvTPHN7TmZS9h8tBDWg/kRFWPoj6/pQmDOWBTJI/yI7thviUU6DZsR75dZ3Bk5o5TAjxHD9bPP65jGUyR9OUQlEt0KAuAw3rBswSSRmqQQ1ZfsmQNg0cMmWgnO0z5YS1yP4hJzLLvTG+I+sDX0tq9dwpFv2r1GHJTbYLTqUhaEd6HRX8YgvC0j5h6qVouS0gBtqF4+SAG6/cojijljB6dhY8u2TVeZH3Fv7ODBj2bEQtJsdNL4w/bqyybnqvacJimYGU6j3C9vrlXIWImwtQ6tSzv4UM7MQvHb815BBZyt50MkmWSfz2QMUWu0zLq5ZJY=
