version: '3.3'
services:
  zipkin:
    image: openzipkin/zipkin
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - back_net
      - front_net
    ports:
      - "9411:9411"
  fluentd:
    image: ${USER_NAME}/fluentd
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - back_net
      - front_net
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:7.4.0
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
      - ELASTIC_CLUSTER=false
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=es01
      - discovery.type=single-node
    networks:
      - back_net
      - front_net
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.4.0
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - back_net
      - front_net
    ports:
      - "5601:5601"

networks:
  front_net:
    external: true
  back_net:
    external: true
