version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db
  ui:
    image: ${USER_NAME}/ui:${VER}
    ports:
      - ${EXT_P}:${INT_P}/tcp
    networks:
      - front_net
      - back_net
  post:
    image: ${USER_NAME}/post:${VER}
    networks:
      - back_net
      - front_net
  comment:
    image: ${USER_NAME}/comment:${VER}
    networks:
      - back_net
      - front_net
volumes:
  post_db:

networks:
  front_net:
    external: true
  back_net:
    external: true
